//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannedTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlannedTb()
        {
            this.Task = new HashSet<TaskTb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string GameServer { get; set; }
        public int State { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int TaskSum { get; set; }
        public int TaskImmVpn { get; set; }
        public int TaskWideVpn { get; set; }
        public string RegisterArr { get; set; }
        public string RemainArr { get; set; }
        public int PriorityId { get; set; }
        public int GameId { get; set; }
        public int UserId { get; set; }
        public bool ModHard { get; set; }
        public bool ModVPN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTb> Task { get; set; }
        public virtual PriorityTb Priority { get; set; }
        public virtual GameTb Game { get; set; }
        public virtual UserTb User { get; set; }
    }
}
