//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTb
    {
        public int Id { get; set; }
        public int PlannedId { get; set; }
        public int PriorityId { get; set; }
        public int ExecutingNum { get; set; }
        public int CancelNum { get; set; }
        public int ErrorNum { get; set; }
        public int TaskSum { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public int State { get; set; }
        public int GameId { get; set; }
    
        public virtual PlannedTb Planned { get; set; }
        public virtual PriorityTb Priority { get; set; }
        public virtual GameTb Game { get; set; }
    }
}
