//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Plan
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool ModHard { get; set; }
        public bool ModVpn { get; set; }
        public string TaskNewArr { get; set; }
        public string TaskKeepArr { get; set; }
    
        public virtual tb_Game tb_Game { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
